name: Delete environment

on:
  delete:
    branches:
      - main
      - develop
      - 'feature/*'

jobs:
  delete-environment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      -
        name: Create friendly branch name
        run: |
          BRANCH=$(cat ${{ github.event_path }} | jq --raw-output '.ref')
          BRANCH_NAME=`echo $BRANCH | tr "[:upper:]" "[:lower:]" | sed -e 's/\//-/g'`
          echo $BRANCH_NAME
          echo "BRANCH_NAME_CLEAN=$(echo $BRANCH_NAME)" >> $GITHUB_ENV

      - name: Setup kubeconfig
        env:
          SECTION_K8S_API_URL: "${{ secrets.SECTION_K8S_API_URL }}"
          SECTION_API_TOKEN: "${{ secrets.SECTION_API_TOKEN }}"
        run: |
          ./ci/init-kube.sh
          echo 'KUBECONFIG<<EOF' >> $GITHUB_ENV
          echo $(cat ~/.kube/config | base64) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Delete environment from Quant Cloud
        uses: koslib/helm-eks-action@v1.28.0
        env:
          KUBE_CONFIG_DATA: ${{ env.KUBECONFIG }}
        with:
          command: |
            helm uninstall ${{ env.BRANCH_NAME_CLEAN }}