name: Delete environment

on:
  delete:
    branches:
      - develop
      - 'feature/*'

jobs:
  delete-environment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Create friendly branch name
        run: |
          BRANCH=$(cat ${{ github.event_path }} | jq --raw-output '.ref')
          BRANCH_NAME=`echo ${BRANCH##*/} | tr "[:upper:]" "[:lower:]" | sed "s/[^[:alnum:]]//g"`
          echo $BRANCH_NAME
          echo "BRANCH_NAME_CLEAN=$(echo $BRANCH_NAME)" >> $GITHUB_ENV

      - uses: quantcdn/cloud-init-action@v1.0.0
        env:
          SECTION_K8S_API_URL: "${{ secrets.SECTION_K8S_API_URL }}"
          SECTION_API_TOKEN: "${{ secrets.SECTION_API_TOKEN }}"

      - name: Delete environment from Quant Cloud
        uses: koslib/helm-eks-action@v1.28.0
        env:
          KUBE_CONFIG_DATA: ${{ env.KUBECONFIG }}
        with:
          command: |
            helm uninstall ${{ env.BRANCH_NAME_CLEAN }}